/**
 * DINOv3 CHM PoC Visualization
 * 
 * This script visualizes a 1024x1024 Canopy Height Model (CHM) chip 
 * generated by Meta's DINOv3 (CHMv2) model and compares it with the 
 * global Meta CHM v1 and v2 datasets.
 */

var chmPath = 'gs://akveg-data/vhr/nome_beaver/processed/20100823_213936_WV02_1030010006605800/poc_chm_chip_20260319.tif';
var psPath = 'gs://akveg-data/vhr/nome_beaver/processed/20100823_213936_WV02_1030010006605800/212_pansharpen/PS_TOA_00p50m_20100823_213936_WV02_1030010006605800.tif';

// 1. Load Local PoC Data
var chmPoC = ee.Image.loadGeoTIFF(chmPath);
var ps = ee.Image.loadGeoTIFF(psPath);

// 2. Load Meta Global Datasets
// Meta CHM v1 (DINOv2 based)
var metaV1 = ee.ImageCollection('projects/meta-forest-monitoring-okw37/assets/CanopyHeight').mosaic();

// Meta CHM v2 (DINOv3 based)
var metaV2 = ee.ImageCollection('projects/meta-forest-monitoring-okw37/assets/CanopyHeight_v2').mosaic();

// Visualization Parameters
var chmViz = {
  min: 0,
  max: 20, // 20 meters max for Boreal/Tundra
  palette: ['#f7fcf5','#e5f5e0','#c7e9c0','#a1d99b','#74c476','#41ab5d','#238b45','#006d2c','#00441b']
};

var psViz = {
  bands: ['B2', 'B1', 'B0'], // Red, Green, Blue
  min: 0,
  max: 2000,
  gamma: 1.4
};

// Map Layers
Map.addLayer(ps, psViz, 'Maxar PS (Red/Green/Blue)');
Map.addLayer(metaV1, chmViz, 'Meta CHM v1 (Global 1m)');
Map.addLayer(metaV2, chmViz, 'Meta CHM v2 (Global 1m)');
Map.addLayer(chmPoC, chmViz, 'DINOv3 PoC Chip (Our Inference)');

// Legend (Simple)
print('Canopy Height Legend: 0m (Light) to 20m+ (Dark Green)');

// Center Map on the PoC chip
Map.centerObject(chmPoC, 17);
