/**
 * DINOv3 CHM PoC Visualization
 * 
 * This script visualizes a 1024x1024 Canopy Height Model (CHM) chip 
 * generated by Meta's DINOv3 (CHMv2) model from 0.5m Maxar imagery.
 */

var chmPath = 'gs://akveg-data/vhr/nome_beaver/processed/20100823_213936_WV02_1030010006605800/poc_chm_chip_20260319.tif';
var psPath = 'gs://akveg-data/vhr/nome_beaver/processed/20100823_213936_WV02_1030010006605800/212_pansharpen/PS_TOA_00p50m_20100823_213936_WV02_1030010006605800.tif';

// Load CHM Chip
var chm = ee.Image.loadGeoTIFF(chmPath);

// Load Reference PS (Red, Green, Blue bands - assuming 3, 2, 1 for WorldView-2)
var ps = ee.Image.loadGeoTIFF(psPath);

// Visualization Parameters
var chmViz = {
  min: 0,
  max: 20, // 20 meters max for Boreal/Tundra
  palette: ['#f7fcf5','#e5f5e0','#c7e9c0','#a1d99b','#74c476','#41ab5d','#238b45','#006d2c','#00441b']
};

var psViz = {
  bands: ['B2', 'B1', 'B0'], // GEE loadGeoTIFF gives B0, B1, B2...
  min: 0,
  max: 2000,
  gamma: 1.4
};

// Map Layers
Map.addLayer(ps, psViz, 'Maxar PS (Red/Green/Blue)');
Map.addLayer(chm, chmViz, 'DINOv3 Canopy Height (m)');

// Legend (Simple)
print('Canopy Height Legend: 0m (Light) to 20m+ (Dark Green)');

// Center Map
Map.centerObject(chm, 17);
